### ISSUE TITLE
Problems displaying wind speed

### ISSUE THREAD

**Issue by PuccioOnee** [KristjanESPERANTO/MMM-OneCallWeather#22]
I can't understand why the wind data isn't being written. only gods only white spheres with arrow

![Image](https://github.com/user-attachments/assets/68afc605-25a7-480a-a699-736bacc25cbd)

**Comment by KristjanESPERANTO** [comment]
The wind speed has a black color and should be in the white sphere (which shows the wind direction).

The CSS for this is a bit hacky, therefore it doesn't fit on every system.

Add this to your `custom.css`:

```css
.MMM-OneCallWeather .wind-speed {
    color: white;
    top: -5px;
}
```

Whit this you should see the wind speed. And you could position it where you want it.
