### ISSUE TITLE
Enlarge the size of the "bubble"

### ISSUE THREAD

**Issue by KristjanESPERANTO** [KristjanESPERANTO/MMM-OneCallWeather#9]
hello, do you know how I can enlarge the size of the "bubble" or there is the wind speed, thank you for your help

![1706648324980-cc5eaf4e-5689-4b3d-9046-0a20229972bc-image](https://github.com/KristjanESPERANTO/MMM-OneCallWeather/assets/28225963/90be58a1-6925-4c6b-8cf7-fe076832eb81)

_Originally posted by @Manu85340 in https://github.com/KristjanESPERANTO/MMM-OneCallWeather/issues/8#issuecomment-1917920424_

**Comment by KristjanESPERANTO** [comment]
@Manu85340 Please always open a new issue when you start a new topic.

You can try add something like this in your `custom.css`:

```css
.weather-icon > span > img {
  height: 80px;
  padding: 0 12px;
}

.weather-icon > p {
  top: -65px !important;
  left: 2px !important;
}
```
